# REad the Docs config

# python version
python:
  version: 3.7
  pip_install: True

# build a PDF
formats:
  - none

# use a conda environment file
conda:
  file: documentation/readthedocs-environment.yml